# Use the official Nginx image as the base image
FROM nginx:alpine

# Install git to clone the repository
RUN apk add --no-cache git

# Clone the website from GitHub
RUN git clone https://github.com/spiritual-gif2/carvilla.git /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
